// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uniceps.Entityframework.DbContexts;


#nullable disable

namespace Unicepse.Entityframework.Migrations.SqliteMigrations
{
    [DbContext(typeof(SqliteUnicepsContext))]
    [Migration("20250302101255_removeRec")]
    partial class removeRec
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("EmployeeSport", b =>
                {
                    b.Property<int>("SportsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SportsId", "TrainersId");

                    b.HasIndex("TrainersId");

                    b.ToTable("EmployeeSport");
                });

            modelBuilder.Entity("Unicepse.Core.Models.Authentication.AuthenticationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LoginDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("authenticationLogs");
                });

            modelBuilder.Entity("Unicepse.Core.Models.Authentication.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Unicepse.Core.Models.DailyActivity.DailyPlayerReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DataStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLogged")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTakenKey")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeyNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("loginTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("logoutTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("DailyPlayerReport");
                });

            modelBuilder.Entity("Unicepse.Core.Models.Employee.Credit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("CreditValue")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmpPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpPersonId");

                    b.ToTable("Credit");
                });

            modelBuilder.Entity("Unicepse.Core.Models.Employee.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Balance")
                        .HasColumnType("REAL");

                    b.Property<int>("BirthDate")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("GenderMale")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSecrtaria")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTrainer")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Parcent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParcentValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("Salary")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SalaryValue")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Unicepse.Core.Models.Employee.TrainerDueses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountSubscription")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Credits")
                        .HasColumnType("REAL");

                    b.Property<double>("CreditsCount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Parcent")
                        .HasColumnType("REAL");

                    b.Property<double>("Salary")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalSubscriptions")
                        .HasColumnType("REAL");

                    b.Property<int?>("TrainerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainerDueses");
                });

            modelBuilder.Entity("Unicepse.Core.Models.Expenses.Expenses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("RecipientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("isManager")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Unicepse.Core.Models.GymProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GymId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GymName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Logo")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GymProfile");
                });

            modelBuilder.Entity("Unicepse.Core.Models.License", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GymId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plan")
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubscribeDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubscribeEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("Unicepse.Core.Models.Metric.Metric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CheckDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Chest")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DataStatus")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Hieght")
                        .HasColumnType("REAL");

                    b.Property<double>("Hips")
                        .HasColumnType("REAL");

                    b.Property<double>("L_Arm")
                        .HasColumnType("REAL");

                    b.Property<double>("L_Humerus")
                        .HasColumnType("REAL");

                    b.Property<double>("L_Leg")
                        .HasColumnType("REAL");

                    b.Property<double>("L_Thigh")
                        .HasColumnType("REAL");

                    b.Property<double>("Nick")
                        .HasColumnType("REAL");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("R_Arm")
                        .HasColumnType("REAL");

                    b.Property<double>("R_Humerus")
                        .HasColumnType("REAL");

                    b.Property<double>("R_Leg")
                        .HasColumnType("REAL");

                    b.Property<double>("R_Thigh")
                        .HasColumnType("REAL");

                    b.Property<double>("Shoulders")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Waist")
                        .HasColumnType("REAL");

                    b.Property<double>("Wieght")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Metrics");
                });

            modelBuilder.Entity("Unicepse.Core.Models.Payment.PayReferance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerTrainingId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RefDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerTrainingId");

                    b.ToTable("PayReferance");
                });

            modelBuilder.Entity("Unicepse.Core.Models.Payment.PlayerPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoverDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DataStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Des")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("From")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PayDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("PaymentValue")
                        .HasColumnType("REAL");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("To")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("PlayerPayments");
                });

            modelBuilder.Entity("Unicepse.Core.Models.Player.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BirthDate")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DataStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("GenderMale")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Hieght")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsSubscribed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTakenContainer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("SubscribeDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubscribeEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Unicepse.Core.Models.Sport.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DailyPrice")
                        .HasColumnType("REAL");

                    b.Property<int>("DaysCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DaysInWeek")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sports");
                });

            modelBuilder.Entity("Unicepse.Core.Models.Subscription.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DataStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DaysCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMoved")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPlayerPay")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStopped")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastCheck")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastPaid")
                        .HasColumnType("TEXT");

                    b.Property<int>("MonthCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OfferDes")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<double>("OfferValue")
                        .HasColumnType("REAL");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrevTrainer_Id")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<double>("PriceAfterOffer")
                        .HasColumnType("REAL");

                    b.Property<double>("PrivatePrice")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("RollDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SportId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TrainerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SportId");

                    b.HasIndex("TrainerId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Unicepse.Core.Models.SyncModel.SyncObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjectData")
                        .HasColumnType("TEXT");

                    b.Property<int>("OperationType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SyncObjects");
                });

            modelBuilder.Entity("Unicepse.Core.Models.TrainingProgram.Exercises", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageId")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Muscel")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("Tid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Unicepse.Core.Models.TrainingProgram.PlayerRoutine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DaysGroupMap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RoutineData")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoutineNo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerRoutine");
                });

            modelBuilder.Entity("Unicepse.Core.Models.TrainingProgram.RoutineItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExercisesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Orders")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("PlayerRoutineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExercisesId");

                    b.HasIndex("PlayerRoutineId");

                    b.ToTable("RoutineItems");
                });

            modelBuilder.Entity("EmployeeSport", b =>
                {
                    b.HasOne("Unicepse.Core.Models.Sport.Sport", null)
                        .WithMany()
                        .HasForeignKey("SportsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unicepse.Core.Models.Employee.Employee", null)
                        .WithMany()
                        .HasForeignKey("TrainersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unicepse.Core.Models.Authentication.AuthenticationLog", b =>
                {
                    b.HasOne("Unicepse.Core.Models.Authentication.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Unicepse.Core.Models.DailyActivity.DailyPlayerReport", b =>
                {
                    b.HasOne("Unicepse.Core.Models.Player.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.HasOne("Unicepse.Core.Models.Subscription.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId");

                    b.Navigation("Player");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Unicepse.Core.Models.Employee.Credit", b =>
                {
                    b.HasOne("Unicepse.Core.Models.Employee.Employee", "EmpPerson")
                        .WithMany()
                        .HasForeignKey("EmpPersonId");

                    b.Navigation("EmpPerson");
                });

            modelBuilder.Entity("Unicepse.Core.Models.Employee.TrainerDueses", b =>
                {
                    b.HasOne("Unicepse.Core.Models.Employee.Employee", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Unicepse.Core.Models.Expenses.Expenses", b =>
                {
                    b.HasOne("Unicepse.Core.Models.Employee.Employee", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("Unicepse.Core.Models.Metric.Metric", b =>
                {
                    b.HasOne("Unicepse.Core.Models.Player.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Unicepse.Core.Models.Payment.PayReferance", b =>
                {
                    b.HasOne("Unicepse.Core.Models.Player.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.HasOne("Unicepse.Core.Models.Subscription.Subscription", "PlayerTraining")
                        .WithMany()
                        .HasForeignKey("PlayerTrainingId");

                    b.Navigation("Player");

                    b.Navigation("PlayerTraining");
                });

            modelBuilder.Entity("Unicepse.Core.Models.Payment.PlayerPayment", b =>
                {
                    b.HasOne("Unicepse.Core.Models.Player.Player", "Player")
                        .WithMany("Payments")
                        .HasForeignKey("PlayerId");

                    b.HasOne("Unicepse.Core.Models.Subscription.Subscription", "Subscription")
                        .WithMany("Payments")
                        .HasForeignKey("SubscriptionId");

                    b.Navigation("Player");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Unicepse.Core.Models.Subscription.Subscription", b =>
                {
                    b.HasOne("Unicepse.Core.Models.Player.Player", "Player")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlayerId");

                    b.HasOne("Unicepse.Core.Models.Sport.Sport", "Sport")
                        .WithMany("PlayerTrainings")
                        .HasForeignKey("SportId");

                    b.HasOne("Unicepse.Core.Models.Employee.Employee", "Trainer")
                        .WithMany("PlayerTrainings")
                        .HasForeignKey("TrainerId");

                    b.Navigation("Player");

                    b.Navigation("Sport");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Unicepse.Core.Models.TrainingProgram.PlayerRoutine", b =>
                {
                    b.HasOne("Unicepse.Core.Models.Player.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Unicepse.Core.Models.TrainingProgram.RoutineItems", b =>
                {
                    b.HasOne("Unicepse.Core.Models.TrainingProgram.Exercises", "Exercises")
                        .WithMany()
                        .HasForeignKey("ExercisesId");

                    b.HasOne("Unicepse.Core.Models.TrainingProgram.PlayerRoutine", "PlayerRoutine")
                        .WithMany("RoutineSchedule")
                        .HasForeignKey("PlayerRoutineId");

                    b.Navigation("Exercises");

                    b.Navigation("PlayerRoutine");
                });

            modelBuilder.Entity("Unicepse.Core.Models.Employee.Employee", b =>
                {
                    b.Navigation("PlayerTrainings");
                });

            modelBuilder.Entity("Unicepse.Core.Models.Player.Player", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Unicepse.Core.Models.Sport.Sport", b =>
                {
                    b.Navigation("PlayerTrainings");
                });

            modelBuilder.Entity("Unicepse.Core.Models.Subscription.Subscription", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Unicepse.Core.Models.TrainingProgram.PlayerRoutine", b =>
                {
                    b.Navigation("RoutineSchedule");
                });
#pragma warning restore 612, 618
        }
    }
}
